"""Recreate FDUser and FDLoginHistory tables

Revision ID: 7cf8b452e4b3
Revises: 
Create Date: 2025-01-08 19:39:55.681003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7cf8b452e4b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fd_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('face_encoding', sa.PickleType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fd_login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['fd_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('FileUploadLibrary')
    op.drop_table('UsersTech')
    op.drop_table('Recommendations_SS')
    op.drop_table('ResourcesSS')
    op.drop_table('FeedbackLib')
    op.drop_table('SearchHistory_SS')
    op.drop_table('ResourcesTech')
    op.drop_table('Resources')
    op.drop_table('FDUser')
    op.drop_table('MandalMaster')
    op.drop_table('UserLog')
    op.drop_table('newbook')
    op.drop_table('FDLoginHistory')
    op.drop_table('Users_SS')
    op.drop_table('ResourceLibrary')
    op.drop_table('Feedback_SS')
    op.drop_table('Bookmarks_SS')
    op.drop_table('images')
    op.drop_table('bookings')
    op.drop_table('mysnippet')
    op.drop_table('BalakMaster')
    op.drop_table('Users')
    op.drop_table('posts')
    op.drop_table('ContactTech')
    op.drop_table('Registration')
    op.drop_table('FileUploadsLibrary')
    op.drop_table('file_uploads')
    op.drop_table('UsersLibrary')
    op.drop_table('FileUploads')
    op.drop_table('BookmarkLib')
    op.drop_table('ResourcesLibrary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ResourcesLibrary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_public', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UsersLibrary.id'], name='FK__Resources__user___32CB82C6', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__Resource__3213E83F507AA354')
    )
    op.create_table('BookmarkLib',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ResourcesLibrary.id'], name='FK__BookmarkL__resou__4D7F7902'),
    sa.ForeignKeyConstraint(['user_id'], ['UsersLibrary.id'], name='FK__BookmarkL__user___4C8B54C9'),
    sa.PrimaryKeyConstraint('id', name='PK__Bookmark__3213E83F08CF8951')
    )
    op.create_table('FileUploads',
    sa.Column('file_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resources.id'], name='FK__FileUploa__resou__4E3E9311', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', name='PK__FileUplo__07D884C6F12A5729')
    )
    op.create_table('UsersLibrary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.NVARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('login_successful', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__UsersLib__3213E83F6D9B7ACE')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('filename', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('path', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('snippet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snippet_id'], ['mysnippet.id'], name='FK_file_uploads_snippet'),
    sa.PrimaryKeyConstraint('id', name='PK__file_upl__3213E83F50597A7E')
    )
    op.create_table('FileUploadsLibrary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('filename', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('path', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ResourcesLibrary.id'], name='FK__FileUploa__resou__369C13AA', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__FileUplo__3213E83FB3FF7B77')
    )
    op.create_table('Registration',
    sa.Column('CustID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Username', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Password', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ConfirmPassword', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('CustID', name='PK__Registra__049E3A8990656E30')
    )
    op.create_table('ContactTech',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('message', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__ContactT__3213E83F608B58AB')
    )
    op.create_table('posts',
    sa.Column('sno', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tagline', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('img_file', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sno', name='PK__posts__DDDF64467C2BD6D1')
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('login_successful', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__Users__3213E83F3E545CD9')
    )
    op.create_table('BalakMaster',
    sa.Column('BalakID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('BalakName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MobileNumber', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BalakAge', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IsActive', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('BalakID', name='PK__BalakMas__3003481D871E9F9B')
    )
    op.create_table('mysnippet',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__mysnippe__3213E83F8E27BCEC')
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reservation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reservation_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('num_people', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__bookings__3213E83F58FA4D69')
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__images__3213E83F9838D71A')
    )
    op.create_table('Bookmarks_SS',
    sa.Column('book_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ss_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('res_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['res_id'], ['ResourcesSS.res_id'], name='FK__Bookmarks__res_i__727BF387', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ss_id'], ['Users_SS.ss_id'], name='FK__Bookmarks__ss_id__7187CF4E', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', name='PK__Bookmark__490D1AE1A2A95146')
    )
    op.create_table('Feedback_SS',
    sa.Column('res_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ss_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['res_id'], ['ResourcesSS.res_id'], name='FK__Feedback___res_i__58BC2184', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ss_id'], ['Users_SS.ss_id'], name='FK__Feedback___ss_id__59B045BD', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('res_id', 'ss_id', name='PK__Feedback__1AD4E9671AC3A5B1')
    )
    op.create_table('ResourceLibrary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_public', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UsersLibrary.id'], name='FK__ResourceL__user___4119A21D'),
    sa.PrimaryKeyConstraint('id', name='PK__Resource__3213E83F8C45C52C')
    )
    op.create_table('Users_SS',
    sa.Column('ss_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ss_id', name='PK__Users_SS__A445C6A212BA0B37')
    )
    op.create_table('FDLoginHistory',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('login_time', sa.DATETIME(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True),
    sa.Column('success', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['FDUser.id'], name='FK_FDLoginHistory_FDUser'),
    sa.PrimaryKeyConstraint('id', name='PK__FDLoginH__3213E83F8ED98D4E')
    )
    op.create_table('newbook',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reservation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reservation_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('num_people', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__newbook__3213E83F12B27B0F')
    )
    op.create_table('UserLog',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.NVARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('login_successful', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__UserLog__3213E83FBF8FF2C9')
    )
    op.create_table('MandalMaster',
    sa.Column('MandalID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MandalName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IsActive', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MandalID', name='PK__MandalMa__55ACAAF55D71C74D')
    )
    op.create_table('FDUser',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('face_encoding', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__FDUser__3213E83FA1AC0D69')
    )
    op.create_table('Resources',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='FK__Resources__user___68336F3E', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__Resource__3213E83F5787AB02')
    )
    op.create_table('ResourcesTech',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UsersTech.id'], name='FK__Resources__user___253C7D7E'),
    sa.PrimaryKeyConstraint('id', name='PK__Resource__3213E83F7EABD3ED')
    )
    op.create_table('SearchHistory_SS',
    sa.Column('Hisid', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ss_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_query', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('searched_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ss_id'], ['Users_SS.ss_id'], name='FK__SearchHis__ss_id__68F2894D', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Hisid', name='PK__SearchHi__5757B097339A535D')
    )
    op.create_table('FeedbackLib',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ResourcesLibrary.id'], name='FK__FeedbackL__resou__49AEE81E'),
    sa.ForeignKeyConstraint(['user_id'], ['UsersLibrary.id'], name='FK__FeedbackL__user___48BAC3E5'),
    sa.PrimaryKeyConstraint('id', name='PK__Feedback__3213E83FF865C9D8')
    )
    op.create_table('ResourcesSS',
    sa.Column('res_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='FK__Resources__user___4A6E022D', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('res_id', name='PK__Resource__2090B50DD769E09D')
    )
    op.create_table('Recommendations_SS',
    sa.Column('rec_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ss_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('res_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['res_id'], ['ResourcesSS.res_id'], name='FK__Recommend__res_i__6DB73E6A', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ss_id'], ['Users_SS.ss_id'], name='FK__Recommend__ss_id__6CC31A31', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id', name='PK__Recommen__97D3CABDBC661B8E')
    )
    op.create_table('UsersTech',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.NVARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('login_successful', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__UsersTec__3213E83F43092E61')
    )
    op.create_table('FileUploadLibrary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('filename', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('path', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ResourcesLibrary.id'], name='FK__FileUploa__resou__43F60EC8'),
    sa.PrimaryKeyConstraint('id', name='PK__FileUplo__3213E83FEA708C84')
    )
    op.drop_table('fd_login_history')
    op.drop_table('fd_user')
    # ### end Alembic commands ###
